version: "3.7"

services:
  reverse-proxy:
    image: traefik:v3.4.3
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - frontend
      - api
      - phpmyadmin
####################################################################################################
# app
####################################################################################################
  frontend:
    image: 985196657557.dkr.ecr.ap-northeast-1.amazonaws.com/ceeq/frontend:develop
    restart: always
    healthcheck:
      test: 'curl -f -I http://localhost:3000/api/hello || exit 1'
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 20s
    env_file:
      - frontend.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.rule=Host(`ceeq.io`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  api:
    image: 985196657557.dkr.ecr.ap-northeast-1.amazonaws.com/ceeq/backend:develop
    restart: always
    healthcheck:
      test: 'curl -f -I http://localhost/login || exit 1'
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.routers.api.rule=Host(`localhost:8000`)"
      - "traefik.http.routers.api.entrypoints=web"
    env_file:
      - backend.env
    depends_on:
      - db
      - redis

####################################################################################################
# DATABASE (MySQL)
####################################################################################################
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ceeq_develop
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql

####################################################################################################
# phpMyAdmin
####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.ceeq.io`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      # PMA_USER: ${DB_USERNAME}
      # PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306

 ####################################################################################################
# Redis
####################################################################################################
  redis:
    image: "redis:alpine"
    restart: always
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "1000mb", "--maxmemory-policy", "allkeys-lru"]
    mem_limit: 1g
    environment:
      SKIP_FIX_PERMS: 1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  db-data: